apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-worker
  labels:
    {{- include "stereo-spot.labels" . | nindent 4 }}
    app: media-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: media-worker
  template:
    metadata:
      labels:
        app: media-worker
        {{- include "stereo-spot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: media-worker
          image: "{{ .Values.images.mediaWorker | default "stereo-spot-media-worker" }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INPUT_BUCKET_NAME
              value: {{ .Values.aws.inputBucketName | quote }}
            - name: OUTPUT_BUCKET_NAME
              value: {{ .Values.aws.outputBucketName | quote }}
            - name: JOBS_TABLE_NAME
              value: {{ .Values.aws.jobsTableName | quote }}
            - name: SEGMENT_COMPLETIONS_TABLE_NAME
              value: {{ .Values.aws.segmentCompletionsTableName | quote }}
            - name: REASSEMBLY_TRIGGERED_TABLE_NAME
              value: {{ .Values.aws.reassemblyTriggeredTableName | quote }}
            - name: CHUNKING_QUEUE_URL
              value: {{ .Values.queues.chunking | quote }}
            - name: REASSEMBLY_QUEUE_URL
              value: {{ .Values.queues.reassembly | quote }}
            - name: AWS_REGION
              value: {{ .Values.global.awsRegion | quote }}
          resources:
            {{- toYaml .Values.mediaWorker.resources | nindent 12 }}
