apiVersion: v1
kind: Service
metadata:
  name: web-ui
  labels:
    {{- include "stereo-spot.labels" . | nindent 4 }}
    app: web-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.webUi.port }}
      protocol: TCP
      name: http
  selector:
    app: web-ui
